### PR TITLE
relinc/SurePulseDataProcessor #22 fixes filtering issues.

### PR DESCRIPTION
**Pull request by bhalonen**
Adds triangular filter and documentation tests.

### CODE REVIEW

**Comment by markhalonen** [comment]
No behavioral changes^. Just cleanup. I ran unit tests and that worked. I ran it in Trim and that worked. I'm trying to run it from Viewer and it's hanging because the filter is extremely slow if the lowpass value is irrationally small. It freezes up and never recovers. Works good with rational lowpass values.

**Comment by markhalonen** [comment]
I forgot to remove the text listener in the Viewer, fixing in relinc/SurePulseDataProcessor#61

**Comment by markhalonen** [comment]
So if you think the hangups with an irrational lowpass value are acceptable, this is ready to merge. I don't know the feasibility of checking the rationality of user input to avoid crashes.

**Comment by bhalonen** [comment]
Will have to work, for now, I think it eventually works, just takes forever to compute.

**Pull request merged**
