### PR TITLE
Added gut check test for true strain

### PR DESCRIPTION
**Pull request by bhalonen**
Put in the test. Think I got the song and dance down.

### CODE REVIEW

**Comment by bhalonen** [comment]
Looks like the test is failing, I can look into that tonight.

**Comment by markhalonen** [comment]
Ok yeah the manually calculated tension true strain values appear to be incorrect. I'll let you make the correction

**Comment by bhalonen** [comment]
No, I'm thinking the calculations are wrong. True tension strain should be less than engineering strain.

**Comment by markhalonen** [comment]
Ah, duh. My mistake

**Comment by bhalonen** [comment]
Do you like this workflow? Natural review point.

**Pull request merged**
